version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./results/certificate_taxi:/app/results/certificate_taxi
      - ./results/city_partners:/app/results/city_partners
      - ./logs:/app/logs
