version: "3.8"
services:
  app:
    build:
      context: .
      args:
        - WRITE_LOGS_TO_FILE=True
    volumes:
      - ./results/certificate_taxi:/app/results/certificate_taxi
      - ./results/city_partners:/app/results/city_partners
      - ./logs:/app/logs
      - ./regions:/app/regions
    shm_size: '2gb'
