"""Add table

Revision ID: 8a6cb9229179
Revises: 
Create Date: 2023-02-22 20:22:51.203379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6cb9229179'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certified_taxi_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('addres', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certified_taxi_drivers')
    # ### end Alembic commands ###
